#!/usr/bin/env bash
# 3. Redirection

apt-get update -y
apt-get upgrade -y
apt-get install nginx -y

match="server_name _;"
new="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=Ceg1r4KxgT0;\n\t}"
sed -i "/$match/a\\$new" /etc/nginx/sites-available/default
service nginx restart