#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
# with the below requirements
echo -e "8.8.8.8\t\tfacebook.com" > file
sed 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts >> file
sudo cp -f file /etc/hosts
